spring:
  datasource:
    url: jdbc:h2:file:./mem-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
      platform: h2
